### ISSUE TITLE
Module 'discreteseekbar' is local and not on Maven Central

### ISSUE THREAD

**Issue by Mar3h** [HeinrichReimer/material-singleinputform#9]
I can not add this to my project.
Could not resolve all dependencies
![screen shot 2015-05-21 at 3 06 18 pm](https://cloud.githubusercontent.com/assets/4371268/7744167/470d4708-ffcb-11e4-9d95-d3e2759badf3.png)

**Comment by HeinrichReimer** [comment]
I guess you forgot adding Maven and jCenter as repositories.

**Comment by Mar3h** [comment]
I already added both

**Comment by HeinrichReimer** [comment]
This may happen because i use discreetseekbar as a local module inside the library. Still odd why Gradle can't resolve this. I currently have not much time to work on that, would be great if you submit a pull request

**Comment by HeinrichReimer** [comment]
Did you include material-singleinputform as a Maven dependency or did you download the source code from GitHub?

**Comment by Mar3h** [comment]
I added as Maven dependency

**Comment by frostymarvelous** [comment]
same issue here. I opened an issue before finding this https://github.com/HeinrichReimer/material-singleinputform/issues/10 

I think you need to publish discreteseekbar as a separate dependency.

**Comment by HeinrichReimer** [comment]
The developer of dicreetseekbar @AnderWeb is planning to upload his library to jCenter. I'll change the dependency then.
Keep this issue open to track progress.

**Comment by frostymarvelous** [comment]
I saw this here https://bintray.com/anderweb/maven/discrete-seekbar/view

**Comment by AnderWeb** [comment]
I've not yet added discreteSeekbar to jCenter because I'm currently merging PRs and tweaking some things.
The current bintray aar should not be used as a dependency yet, sorry, it's not complete

**Comment by frostymarvelous** [comment]
Thanks for the clarification @AnderWeb.

Anyway, for those who need to be able to work with this lib in the meantime, I used a work around. It isn't perfect, but at least, I finally got it to run. The other alternative being cloning the library and including as a module in your project.



First, create a recreate this folder dir `C:/Users/{{ USERNAME }}/AppData/Local/Android/sdk/extras/android/m2repository/Android-SingleInputForm/discreteseekbar/unspecified/`

Then download this jar (renamed from aar) https://s3-eu-west-1.amazonaws.com/edzibanpa/discreteseekbar-unspecified.jar

Update your gradle file like so by adding the `packagingOptions`

	android {
		compileSdkVersion 22
		buildToolsVersion "22.0.1"


		packagingOptions {
			exclude 'AndroidManifest.xml'
		}
	}

*Caveats*
 - I am using the latest build tools.
- You cannot use the  `SeekBarStep`. Didn't bother to debug since I don't need it

**Comment by frostymarvelous** [comment]
In this POC, I have merged the DiscreteSeekbar as part of the library module https://github.com/frostymarvelous/material-singleinputform/tree/DiscreteSeekBarWorkaround

**Comment by frostymarvelous** [comment]
Finally released on jcenter 

compile 'org.adw.library:discrete-seekbar:1.0.0'

**Comment by sirvon** [comment]
yo @frostymarvelous thanks man!

**Comment by sirvon** [comment]
i added the seekbar dep but still go the error.
with the seekbar on jcenter how do I cleanly use this lib with it?

**Comment by marekyggdrasil** [comment]
@sirvon same situation here, added dependency and still getting same error

**Comment by marekyggdrasil** [comment]
If I build my project without singleinputform 2.0 it builds correctly.
To make sure that discrete-seekbar is there I import it just like @HeinrichReimer you do in your SeekBarStep:

`import org.adw.library.widgets.discreteseekbar.DiscreteSeekBar;`

And I create an instance of it. Everything builds just fine. Also in my build.gradle I reference it in same way as build.gradle in singleinputlibrary:

`compile 'org.adw.library:discrete-seekbar:1.0.0'`

However once I add this:

`compile 'com.heinrichreimersoftware.singleinputform:library:2.0'`

I cannot sync the project no more because of:

`Error:Failed to resolve: Android-SingleInputForm:discreteseekbar:unspecified`

I don't really get where this failed to resolve comes from since as I proved on beginning, I reference it in same way as you and it builds fine.

**Comment by marekyggdrasil** [comment]
I made it work. Turned out that using release `2.1.0` solved the issue, just like I predicted. Here is a little tutorial I prepared that details how to build `material-singleinputform` release `2.1.0` library jar file.

From [here](  https://github.com/HeinrichReimer/material-singleinputform/releases ) download compressed release `2.1.0`, uncompress it somewhere on your machine and go to this directory.

Open Android Studio and then:

`Tools -> Android -> SDK Manager`

In `SKD Platforms` tab check one with API Level 23 and in `SDK Build Tools` tab check `Android SDK Build Tools`. Click on `Apply` to install.

You need to know where is the directory with all you Android stuff on your system, in my case it is:

`~/adt-bundle-linux-x86-20131030`

Make sure you have `android-23` directory using:

`ls ~/adt-bundle-linux-x86-20131030/sdk/platforms/`

Make sure you have 23.0.x build-tools:

`ls ~/adt-bundle-linux-x86-20131030/sdk/build-tools/`

If instead of 23.0.0 you have 23.0.2 (my case), you will have to edit files

```
example/build.gradle 
library/build.gradle 
```

And there change `buildToolsVersion "23.0.0"` to  `buildToolsVersion "23.0.2"`

Now set global android home system variable to the one that corresponds to your SDK, like that:

`set ANDROID_HOME=~/adt-bundle-linux-x86-20131030/sdk`

And create in singleinputform project directory create file `local.properties` where you also specify where SDK is.

`sdk.dir=../../../adt-bundle-linux-x86-20131030/sdk`

As you may noticed, here it must be a relative path, the reason is that this string will be append to project root directory.

If you have gradle installed simple call

`gradle build`

I have downloaded a binary from gradle website so I called it from relative path to downloaded gradle binary

`../gradle-2.8/bin/gradle build`

If your build was success, make sure you have the `aar` file:

`ls library/build/outputs/aar/`

you will find file `library-release.aar`, now extract jar from aar:

`unzip library/build/outputs/aar/library-release.aar`

Now a `classes.jar` file appear in root directory of build project.
You can rename this file to whatever you like and you can copy it to your project libs directory in

`path-to-your-projects/YourProject/app/libs/`

Comment previous entries in build.gradle

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.0.1'
//    compile 'org.adw.library:discrete-seekbar:1.0.0'
//    compile 'com.heinrichreimersoftware.singleinputform:library:2.0.0'
}
```

For test I did extend my `MainActivity` to `SingleInputFormActivity`. Project builds correctly.

CONCLUSION: Once release `2.1.0` will appear in repo everything should be fine.
